# Generated by Django 5.2.3 on 2025-07-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_alter_comment_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
