# Generated by Django 5.2.3 on 2025-07-08 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_alter_snippet_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2025, 7, 8, 9, 39, 46, 521864, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
