# Generated by Django 5.2.3 on 2025-08-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0016_snippetsubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippetsubscription',
            options={'ordering': ['-created_at']},
        ),
    ]
