# Generated by Django 5.2.3 on 2025-08-25 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0017_alter_snippetsubscription_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippetsubscription',
            name='snippet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='MainApp.snippet'),
        ),
        migrations.AlterField(
            model_name='snippetsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippet_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
